### ISSUE TITLE
pip install -r requirements.txt fails

### ISSUE THREAD

**Issue by kazeevn** [Curtaz/MaMoMo#3]
Hello!

I'm following the README to install the Python libraries. pip fails as following:
```
coder@production-env-e597a94ff01e4fe79905ba7bcd4bbac5:~/project$ pip install -r requirements.txt 
Defaulting to user installation because normal site-packages is not writeable
ERROR: Invalid requirement: '_libgcc_mutex=0.1=main' (from line 4 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?
```

pip is the latest version:
```
coder@production-env-e597a94ff01e4fe79905ba7bcd4bbac5:~/project$ pip --version
pip 23.3.1 from /home/coder/.local/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by Curtaz** [comment]
Apologies for the inconvenience, 
The original environment was built using conda, and requirements were extracted from it. My fault for believing the requirements file was compatible with wheel. I have updated ```requirements.txt``` and the ```README```.  Let me know if you still encounter issues

**Comment by kazeevn** [comment]
The new file works. Thank you!
